name: CCEbridge
main: com.crossge.ccebridge.CCEbridge
version: 1.1.0
website: http://crossge.com
description: Adds an bridge for buying ranks from essentials gm
authors: [Cross Gaming Development Team]

commands:
   setrankprice:
      description: Sets the price of a rank
      usage: /<command> <rankname> <price>
      permission: CCEbridge.srp
      aliases: [setrankcost, setrankworth, srp, src, srw]
   buyrank:
      description: Buys <rankname>
      usage: /<command> <rankname>
      permission: CCEbridge.buy 
      aliases: [buyr, brank]
   rankprices:
      description: Shows the prices of the ranks
      usage: /<command> <page>
      permission: CCEbridge.prices
      aliases: [rprices]
   setcommandprice:
      description: Sets the price of a command and sets minimum rank to <rank>
      usage: /<command> <commandname> <price> <rank>
      permission: CCEbridge.scp
      aliases: [setcommandcost, setcommandworth, setcmdprice, setcmdcost, setcmdworth]
   buycommand:
      description: Buys <command>
      usage: /<command> <command>
      permission: CCEbridge.buycmd 
      aliases: [buycmd]
   commandprices:
      description: Shows the prices of the commands only shows those that you are able to buy
      usage: /<command> <page>
      permission: CCEbridge.cmdprices
      aliases: [cmdprices]
      
permissions:
    CCEbridge.*:
        description: The Mainframe of CCEbridge's command structure
        children:
            CCEbridge.prices: true
            CCEbridge.buy: true
            CCEbridge.srp: true
            CCEbridge.scp: true
            CCEbridge.buycmd: true
            CCEbridge.cmdprices: true
    CCEbridge.prices:
        description: Prices of a rank.
        default: true
    CCEbridge.buy:
        description: Buys a rank.
        default: true
    CCEbridge.buycmd:
        description: Buys a command.
        default: true
    CCEbridge.cmdprices:
        description: Prices of commands.
        default: true
    CCEbridge.srp:
        description: Sets a price for a rank.
        default: op
    CCEbridge.scp:
        description: Sets a price for a command and rank minimum rank needed.
        default: op