name: Necessities
main: com.github.CorporateCraft.necessities.Necessities
version: 0.3
website: http://crossge.com
description: Adds necessities of a server
authors: [CrossGaming Development Team]

commands:   
   tpaccept:
      description: Accepts a teleport if player is not specified will use last offered tp request
      usage: /<command> <player who offered tp>
      permission: Necessities.tpaccept
      aliases: [teleportaccept]  
   tpa:
      description: Sends a request to <player> to let you teleport to them
      usage: /<command> <player who offered tp>
      permission: Necessities.tpa
   tpahere:
      description: Sends a request to <player> to teleport to you
      usage: /<command> <player>
      permission: Necessities.tpahere
   tp:
      description: Teleports to <player>
      usage: /<command> <player>
      permission: Necessities.tp
   tphere:
      description: Teleports <player> to you
      usage: /<command> <player>
      permission: Necessities.tphere
   tpdeny:
      description: Deny a teleport if player is not specified will use last offered tp request
      usage: /<command> <player who offered tp>
      permission: Necessities.tpdeny
      aliases: [teleportdeny, tpdecline, teleportdecline]  
   rules:
      description: Shows you the rules
      usage: /<command>
      permission: Necessities.rules  
   motd:
      description: Shows you the motd
      usage: /<command>
      permission: Necessities.motd
   permissions:
      description: Shows you the perm for <commandname>
      usage: /<command> <commandname>
      permission: Necessities.perms
   ops:
      description: Shows the server ops
      usage: /<command>
      permission: Necessities.ops
      aliases: [operators]
   banned:
      description: Shows who is banned from the server
      usage: /<command>
      permission: Necessities.banned
   bannedips:
      description: Shows the ips that are banned from a server
      usage: /<command>
      permission: Necessities.bannedips
   kill:
      description: Kills <name> with an optional message
      usage: /<command> <name> <message>
      permission: Necessities.kill
   suicide:
      description: Commits suicide
      usage: /<command>
      permission: Necessities.suicide
   ragequit:
      description: Ragequits the server
      usage: /<command>
      permission: Necessities.ragequit
   enchant:
      description: Enchants the item in hand
      usage: /<command> <enchantment_name> <level>
      permission: Necessities.enchant
   warn:
      description: Warns a player for <reason>
      usage: /<command> <player> <reason>
      permission: Necessities.warn
   gamemode:
      description: Sets a players gamemode to <gamemode>
      usage: /<command> <gamemode> <player>
      permission: Necessities.gamemode
      aliases: [gm]
   reload:
      description: Reloads the server or a plugin
      usage: /<command> <pluginname>
      permission: Necessities.reload
   kick:
      description: Kicks a player for <reason>
      usage: /<command> <name> <reason>
      permission: Necessities.kick
   ban:
      description: Bans a player for <reason>
      usage: /<command> <name> <reason>
      permission: Necessities.ban
   banip:
      description: IpBans a player for <reason>
      usage: /<command> <name> <reason>
      permission: Necessities.banip
   fly:
      description: Toggles fly mode for youself or <name>
      usage: /<command> <name>
      permission: Necessities.fly
   god:
      description: Toggles god mode for youself or <name>
      usage: /<command> <name>
      permission: Necessities.god
   feed:
      description: Feeds youself or <name>
      usage: /<command> <name>
      permission: Necessities.feed
   heal:
      description: Heals youself or <name>
      usage: /<command> <name>
      permission: Necessities.heal
   global:
      description: Sends a message to global chat
      usage: /<command> <message>
      permission: Necessities.gc
      aliases: [gc]
   slap:
      description: Slaps <nane> sky high
      usage: /<command> <name>
      permission: Necessities.slap
   potion:
      description: Potion stuff
      usage: /<command> <name/effect> <effect/time> <time/power> <power>
      permission: Necessities.potion
   imp:
      description: Fake messages
      usage: /<command> <message>
      permission: Necessities.imp
      aliases: [impersonate]

permissions:
    Necessities.*:
        description: The Mainframe of Necessities' command structure
        children:
            Necessities.tpaccept: true
            Necessities.tpdeny: true
            Necessities.tpa: true
            Necessities.tpahere: true
            Necessities.tp: true
            Necessities.tphere: true
            Necessities.rules: true
            Necessities.motd: true
            Necessities.perms: true
            Necessities.ops: true
            Necessities.banned: true
            Necessities.bannedips: true
            Necessities.kill: true
            Necessities.suicide: true
            Necessities.ragequit: true
            Necessities.enchant: true
            Necessities.warn: true
            Necessities.gamemode: true
            Necessities.reload: true
            Necessities.kick: true
            Necessities.ban: true
            Necessities.banip: true
            Necessities.fly: true
            Necessities.god: true
            Necessities.feed: true
            Necessities.heal: true
            Necessities.gc: true
            Necessities.slap: true
            Necessities.potion: true
            Necessities.imp: true
            Necessities.caps: true
            Necessities.language: true
            Necessities.spamchat: true
            Necessities.spamcommands: true
    Necessities.tpaccept:
        description: Allows you to accept teleports.
        default: true
    Necessities.tpdeny:
        description: Allows you to deny teleports.
        default: true
    Necessities.tpa:
        description: Allows you to request teleportation.
        default: true
    Necessities.tpahere:
        description: Allows you to request summons.
        default: true
    Necessities.rules:
        description: Allows you to read the rules.
        default: true
    Necessities.motd:
        description: Allows you to read the motd.
        default: true
    Necessities.suicide:
        description: Allows you to commit suicide.
        default: true
    Necessities.ops:
        description: Allows you to see the current oplist.
        default: true
    Necessities.banned:
        description: Allows you to see the current banned players.
        default: true
    Necessities.bannedips:
        description: Allows you to see the current banned ips.
        default: true
    Necessities.ragequit:
        description: Allows you to ragequit the server.
        default: true
    Necessities.gc:
        description: Allows you to send a message to global.
        default: true
    Necessities.enchant:
        description: Allows you to enchant items.
        default: op
    Necessities.warn:
        description: Allows you to warn players.
        default: op
    Necessities.tp:
        description: Allows you to teleport to people.
        default: op
    Necessities.tphere:
        description: Allows you to summon people.
        default: op
    Necessities.perms:
        description: Allows you to see a commands permissions.
        default: op
    Necessities.kill:
        description: Allows you to kill someone with an optional message.
        default: op
    Necessities.gamemode:
        description: Allows you to change a persons gamemode
        default: op
    Necessities.reload:
        description: Allows you to reload the server.
        default: op
    Necessities.kick:
        description: Allows you to kick a player.
        default: op
    Necessities.ban:
        description: Allows you to ban a player.
        default: op
    Necessities.banip:
        description: Allows you to ipban a player.
        default: op
    Necessities.fly:
        description: Allows you to fly.
        default: op
    Necessities.god:
        description: Allows you to become a god.
        default: op
    Necessities.feed:
        description: Allows you to feed yourself.
        default: op
    Necessities.heal:
        description: Allows you to heal yourself.
        default: op
    Necessities.slap:
        description: Allows you to slap a player.
        default: op
    Necessities.potion:
        description: Allows you to do potion effects.
        default: op
    Necessities.imp:
        description: Allows you to do imp people.
        default: op
    Necessities.caps:
        description: Allows you to use caps.
        default: op
    Necessities.language:
        description: Allows you to use bad language.
        default: op
    Necessities.spamchat:
        description: Allows you to spam chat.
        default: op
    Necessities.spamcommands:
        description: Allows you to spam commands.
        default: op