name: KillWithMessage
main: com.github.CorporateCraft.killwithmessage.KillWithMessage
version: 1.0.0.0
website: http://corporatecraft.net
description: Adds the ability to have a death message with cmd other then $name died
authors: [CorporateCraft Development Team]

commands:
   killwithmessage:
      description: Kills someone with a message
      usage: /<command> <player> <message>
      permission: KillWithMessage.kill
      aliases: [killwmsg,killmsg]

permissions:
    KillWithMessage.kill:
        description: Allows you to kill someone with an optional message
        default: ops