name: OpsAndBanned
main: com.github.CorporateCraft.opsandbanned.OpsAndBanned
version: 1.0.0.1
website: http://corporatecraft.net
description: Adds the commands /ops, /banned, and /bannedips.
authors: [CorporateCraft Development Team]

commands:
   ops:
      description: Shows the server ops
      usage: /<command>
      permission: OpsAndBanned.ops
   banned:
      description: Shows who is banned from the server
      usage: /<command>
      permission: OpsAndBanned.banned
   bannedips:
      description: Shows the ips that are banned from a server
      usage: /<command>
      permission: OpsAndBanned.bannedips

permissions:
    OpsAndBanned.*:
        description: Gives access to all opsandbanned commands
        children:
            OpsAndBanned.ops: true
            OpsAndBanned.banned: true
            OpsAndBanned.bannedips: true
    OpsAndBanned.ops:
        description: Allows you to see the operator list.
        default: true
    OpsAndBanned.banned:
        description: Allows you to see banned players.
        default: true
    OpsAndBanned.bannedips:
        description: Allows you to see banned ips.
        default: true