name: CCEconomy
main: com.github.CorporateCraft.cceconomy.CCEconomy
version: 1.2.2
website: http://corporatecraft.x10.mx
description: Adds an economy system
authors: [CorporateCraft Development Team]

commands:
   bal:
      description: Shows your balance
      usage: /<command> <name>
      permission: CCEconomy.bal
      aliases: [balance,money]
   baltop:
      description: Shows the balance of the top players
      usage: /<command> <page>
      permission: CCEconomy.baltop
      aliases: [balancetop,moneytop]     
   pay:
      description: Pays <name> $<amount>
      usage: /<command> <name> <amount>
      permission: CCEconomy.pay
      aliases: [sendmoney]
   cce:
      description: A variaty of commands to edit someones bal <set>, <take>, <give>, and <reset>
      usage: /<command> <sub command> <name> <amount>
      permission: CCEconomy.editbal   
   setprice:
      description: Sets the price of an to sell
      usage: /<command> <itemname:id:hand> <price> <sell/buy>
      permission: 
      aliases: [setcost, setworth]
   price:
      description: Shows how much money <itemname> is worth to sell
      usage: /<command> <itemname:id:hand> <sell/buy>
      permission: CCEconomy.price
      aliases: [cost, worth]
   buy:
      description: Shows the cost of buying <itemname>
      usage: /<command> <itemname:id:hand> <amount>
      permission: CCEconomy.buy
   sell:
      description: Sells item with the given amount default is all
      usage: /<command> <itemname:id:hand> <amount>
      permission: CCEconomy.sell   
   pricelist:
      description: Shows the prices of the sellable items on the server
      usage: /<command> <page>
      permission: CCEconomy.pricelist
      aliases: [listprices, prices, worths]   
   taccept:
      description: Accept a trade from a player
      usage: /<command> <player who offered trade>
      permission: CCEconomy.taccept
      aliases: [tradeaccept]     
   tdeny:
      description: Deny a trade from a player
      usage: /<command> <player who offered trade>
      permission: CCEconomy.tdeny
      aliases: [tdecline, tradedeny, tradedecline]     
   trade:
      description: Trades an item to someone for $<price> or trades to you
      usage: /<command> <name> <itemname:id> <amount> <price> <theypay:ipay>
      permission: CCEconomy.trade      
   tradeitems:
      description: Trades an item to someone for another item
      usage: /<command> <name> <itemname:id> <amount> <itemname:id> <amount>
      permission: CCEconomy.trade      
      aliases: [tradei]
      
permissions:
    CCEconomy.*:
        description: The Mainframe of CCEconomy's command structure
        children:
            CCEconomy.bal: true
            CCEconomy.baltop: true
            CCEconomy.pay: true
            CCEconomy.price: true
            CCEconomy.buy: true
            CCEconomy.sell: true
            CCEconomy.setprice: true
            CCEconomy.balothers: true
            CCEconomy.editbal: true
            CCEconomy.taccept: true
            CCEconomy.tdeny: true
            CCEconomy.trade: true
            CCEconomy.pricelist: true
    CCEconomy.bal:
        description: Lets you see your own balance.
        default: true
    CCEconomy.baltop:
        description: Allows you to look at the players with the most money.
        default: true
    CCEconomy.pay:
        description: Pays someone some money.
        default: true
    CCEconomy.price:
        description: Allows you to see the price of an item.
        default: true
    CCEconomy.buy:
        description: Allows you to buy items.
        default: true
    CCEconomy.sell:
        description: Allows you to sell items.
        default: true
    CCEconomy.taccept:
        description: Allows you to accept trades.
        default: true
    CCEconomy.tdeny:
        description: Allows you to deny trades.
        default: true
    CCEconomy.trade:
        description: Allows you to trade with players.
        default: true
    CCEconomy.pricelist:
        description: Allows you to see the pricelist.
        default: true
    CCEconomy.setprice:
        description: Allows you to set cost of an item.
        default: op
    CCEconomy.balothers:
        description: Allows you to look at other peoples balances.
        default: op
    CCEconomy.editbal:
        description: Allows you to edit other players balances.
        default: op